server:
  port: 8090
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: root
    platform: h2
    url: jdbc:h2:file:./data/fileDb
    username: root
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true